apiVersion: batch/v1
kind: CronJob
metadata:
  name: registry-watcher
  namespace: default
spec:
  schedule: '*/1 * * * *'
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: kubewatcher-sa
          restartPolicy: OnFailure
          containers:
          - name: registry-watcher
            image: preetamsad/registry-watcher
