apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubewatcher-rb
  namespace: default
subjects:
- kind: ServiceAccount
  name: kubewatcher-sa
  namespace: default
roleRef:
  kind: Role
  name: kubewatcher-role
  apiGroup: rbac.authorization.k8s.io
