apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imagelists.kubewatcher.internal
spec:
  group: kubewatcher.internal
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                images:
                  type: array
                  items:
                    type: string
  names:
    plural: imagelists
    singular: imagelist
    kind: ImageList
    shortNames:
      - imgl
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imagedepomaps.kubewatcher.internal
spec:
  group: kubewatcher.internal
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                mappings:
                  type: object
                  additionalProperties:
                    type: array
                    items:
                      type: string
  names:
    plural: imagedepomaps
    singular: imagedepomap
    kind: ImageDepoMap
    shortNames:
      - imgdm
