apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: kubewatcher-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["kubewatcher.internal"]
  resources: ["imagelists", "imagedepomaps", "updepolists", "imagedigestmaps"]
  verbs: ["get", "watch", "list", "create", "update"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  resourceNames: ["registry-watcher"]
  verbs: ["get", "list"]
