apiVersion: kubewatcher.internal/v1alpha1
kind: ImageList
metadata:
  name: image-list
  namespace: default
spec:
  images: []
---

apiVersion: kubewatcher.internal/v1alpha1
kind: ImageDepoMap
metadata:
  name: image-depo-map
  namespace: default
spec:
  mappings: {}
---

apiVersion: kubewatcher.internal/v1alpha1
kind: UpDepoList
metadata:
  name: updepo-list
  namespace: default
spec:
  depos: []
---

apiVersion: kubewatcher.internal/v1alpha1
kind: ImageDigestMap
metadata:
  name: image-digest-map
  namespace: default
spec:
  mappings: {}
